# Generated by Django 5.1.3 on 2024-12-06 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fill_level', models.FloatField(default=0)),
                ('location', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_point', models.JSONField()),
                ('instructions', models.JSONField()),
                ('duration', models.IntegerField()),
                ('distance', models.IntegerField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('day_of_the_week', models.IntegerField()),
                ('bins', models.ManyToManyField(related_name='routes', to='bins.bin')),
            ],
        ),
        migrations.AddField(
            model_name='bin',
            name='street',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bins', to='bins.street'),
        ),
        migrations.AddField(
            model_name='street',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='streets', to='bins.zone'),
        ),
    ]
