# Generated by Django 5.1.3 on 2024-12-01 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bins', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='end_point',
            new_name='points',
        ),
        migrations.RemoveField(
            model_name='route',
            name='start_point',
        ),
    ]
