# Generated by Django 5.1.3 on 2024-12-01 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bins', '0002_rename_end_point_route_points_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bin',
            old_name='fullLevel',
            new_name='fillLevel',
        ),
    ]
