# Generated by Django 5.1.3 on 2024-12-01 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bins', '0003_rename_fulllevel_bin_filllevel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='points',
            new_name='bins',
        ),
        migrations.RemoveField(
            model_name='route',
            name='bin',
        ),
        migrations.RemoveField(
            model_name='route',
            name='date',
        ),
        migrations.AddField(
            model_name='route',
            name='starting_point',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
