# Generated by Django 5.1.3 on 2024-12-01 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bins', '0004_rename_points_route_bins_remove_route_bin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='starting_point',
            field=models.JSONField(),
        ),
    ]
