# Generated by Django 5.1.3 on 2024-12-01 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bins', '0005_alter_route_starting_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='route',
            name='duration',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
