# Generated by Django 5.1.3 on 2024-12-01 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bins', '0006_route_date_route_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bin',
            old_name='fillLevel',
            new_name='fill_level',
        ),
    ]
