# Generated by Django 5.1.3 on 2024-12-02 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bins', '0007_rename_filllevel_bin_fill_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='bins',
        ),
        migrations.AddField(
            model_name='route',
            name='bins',
            field=models.ManyToManyField(related_name='routes', to='bins.bin'),
        ),
    ]
