# Generated by Django 5.1.3 on 2024-12-02 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bins', '0008_remove_route_bins_route_bins'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='instructions',
            field=models.JSONField(default='{}'),
            preserve_default=False,
        ),
    ]
